name: Release to GitHub

on:
  push:
    tags: [v*]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Move output jars
      run: |
        pushd ./build/libs
        mv ./UpToDateMod-mc1.7.10-*.jar ./output.jar
        mv ./UpToDateMod-mc1.7.10-*-src.jar ./src.jar
        mv ./UpToDateMod-mc1.7.10-*-dev.jar ./dev.jar
        popd
        
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        
    - name: Upload output jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/libs/output.jar
        asset_name: UpToDateMod-mc1.7.10-${{ github.ref }}.jar
        asset_content_type: application/java-archive
    
    - name: Upload src jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/libs/src.jar
        asset_name: UpToDateMod-mc1.7.10-${{ github.ref }}-src.jar
        asset_content_type: application/java-archive
        
    - name: Upload dev jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/libs/dev.jar
        asset_name: UpToDateMod-mc1.7.10-${{ github.ref }}-dev.jar
        asset_content_type: application/java-archive
